name: Auto approve

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  approve:
    runs-on: ubuntu-22.04
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      contains(github.event.pull_request.labels.*.name, 'auto-approval')
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
