name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: preview-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pages-preview:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        if: github.event.action != 'closed'
        with:
          path: ~/.cache/vcpkg
          key: x64-linux-gcc-${{ hashFiles('vcpkg.json') }}
          restore-keys: x64-linux-gcc-${{ hashFiles('vcpkg.json') }}

      - uses: aminya/setup-cpp@v1
        if: github.event.action != 'closed'
        with:
          compiler: gcc
          cmake: true
          ninja: true
          ccache: true
          doxygen: true
          graphviz: true
          python: true

      - name: Install docs dependencies
        if: github.event.action != 'closed'
        run: |
          pip install -r docs/requirements.txt

      - name: Configure
        if: github.event.action != 'closed'
        run: cmake -S . --preset=x64-linux-gcc -DBUILD_TESTING=OFF -DCODE_COVERAGE=OFF

      - name: Build Docs
        if: github.event.action != 'closed'
        run: cmake --build out/build/x64-linux-gcc --target ss-cpp-docs

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@f31d5aa7b364955ea86228b9dcd346dc3f29c408 # v1
        with:
          source-dir: ./docs/_build/html
