name: Renovate

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/15 0-3 * * 1'
  workflow_dispatch:

jobs:
  renovate:
    container:
      env:
        LOG_LEVEL: debug
        RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: '["^git", "^pip", "^copier", "^find"]'
        RENOVATE_BRANCH_PREFIX: renovate-github/
        RENOVATE_ENABLED: ${{ vars.RENOVATE_ENABLED || true }}
        RENOVATE_ENABLED_MANAGERS: '["pep621", "github-actions", "regex", "pre-commit"]'
        RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
        RENOVATE_PLATFORM: github
        RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
        RENOVATE_REPOSITORY_CACHE: enabled
      image: ghcr.io/renovatebot/renovate:37.318.1-full@sha256:67632eaa3ce95cfe82b647d42a353e55a3559da867efb020a03b9bc61526b519
      options: --user root
    runs-on: ubuntu-22.04
    steps:
      - run: env | sort
      - id: generate-token
        name: Generate a token with GitHub App if App ID exists
        if: vars.BOT_APP_ID
        uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Run Renovate
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN || steps.generate-token.outputs.token }}
          RENOVATE_GIT_AUTHOR: ${{ vars.RENOVATE_GIT_AUTHOR }}
        run: |
          if [ -n "${{ steps.generate-token.outputs.token }}" ] && [ -n "$RENOVATE_GIT_AUTHOR" ]; then
            echo "# :warning: RENOVATE_GIT_AUTHOR is set when using GitHub App token" >> $GITHUB_STEP_SUMMARY
            echo "Normally, RENOVATE_GIT_AUTHOR will be resolved from the token by Renovate. However, if you set RENOVATE_GIT_AUTHOR, it will override the token's git author." >> $GITHUB_STEP_SUMMARY
          fi

          if [ -z "$RENOVATE_TOKEN" ]; then
            echo "RENOVATE_TOKEN is not properly configured, skipping ..."
          else
            renovate $RENOVATE_EXTRA_FLAG
          fi
